GET http://localhost:8181/projets HTTP/1.1


###

POST http://localhost:8181/projets HTTP/1.1
Content-Type: application/json

{
    "titre" : "ximunaxiette",
    "date" : "12-10-2015",
    "description" : "bloubliblam",
    "couverture" : "https://via.placeholder.com/150",
    "images" : "https://via.placeholder.com/150"
}

###

PUT http://localhost:8181/projets/606a29bc-d5ae-4973-ae6c-a55b197b1f7b HTTP/1.1
Content-Type: application/json

{
    "titre" : "hellokolui",
    "date" : "12-10-2020",
    "description" : "balblaqsdfghbla",
    "couverture" : "https://via.placeholder.com/150",
    "images" : "https://via.placeholder.com/150"
}

###

DELETE http://localhost:8181/projets/606a29bc-d5ae-4973-ae6c-a55b197b1f7b HTTP/1.1
Content-Type: application/json

