GET http://localhost:8181/tags HTTP/1.1

###

POST http://localhost:8181/tags HTTP/1.1
Content-Type: application/json

{
    "label" : "Webdesign"
}


###
PUT http://localhost:8181/tags/0dd1432e-17f9-476a-89ae-b96992093499 HTTP/1.1
Content-Type: application/json

{
    "label" : "Front"
}

